# Generated by Django 5.2.5 on 2025-08-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['insurer_name'], name='claims_clai_insurer_b6e0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['discharge_date'], name='claims_clai_dischar_7159fd_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient_name'], name='claims_clai_patient_f7d363_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['billed_amount'], name='claims_clai_billed__f0d2c2_idx'),
        ),
    ]
